### ISSUE TITLE
tap kafka

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/Singer-Most-Wanted#64] opened 2022-10-24 14:29 UTC

**Comment by crowemi** [comment] 2022-10-24 20:12
@pnadolny13, duplicate of #61 ?

**Comment by pnadolny13** [comment] 2022-10-24 21:17
@crowemi yep youre right, this was supposed to be _tap_ kafka. I updated the title!

**Comment by pnadolny13** [comment] 2023-01-20 15:35
A bunch of variants already exist for this https://hub.meltano.com/extractors/tap-kafka so I'm updating it to be "to SDK".

**Closed** 2023-01-20 15:43 UTC
